name: Build & Deploy to Cloud Run

on:
  push:
    branches: ["main"]          # deploy on every push to main
  workflow_dispatch:            # manual trigger button

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    # NEW → proper auth step
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # Setup gcloud after auth
    - name: Set up gcloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # Build Docker image via Cloud Build
    - name: Build container image
      run: |
        gcloud builds submit \
          --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/wasteassistant:${{ github.sha }}

    # Deploy the new revision to Cloud Run
    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: wasteassistant
        image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/wasteassistant:${{ github.sha }}
        region: ${{ secrets.GCP_REGION }}
        allow_unauthenticated: true
