name: Build & Deploy to Cloud Run

on:
  push:
    branches: ["main"]        # deploy on every push to main
  workflow_dispatch:          # manual “Run workflow” button

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    # Authenticate with the JSON key stored in the secret
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # Build *and* deploy straight from the source directory
    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: wasteassistant
        source: .                               # <-- build from current repo
        region: ${{ secrets.GCP_REGION }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        allow_unauthenticated: true
