name: Build & Deploy to Cloud Run

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # Build from source and deploy in one step
    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: wasteassistant                     # existing Cloud Run service
        source: .                                  # build Docker image from repo root
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        region: ${{ secrets.GCP_REGION }}
        flags: --allow-unauthenticated             # keep the service public
